language: scala
sudo: required
jdk:
- openjdk8
scala:
- 2.11.8

before_script:
- sudo chmod +x /usr/local/bin/sbt

script:
- travis_wait 30 sbt compile coverage test scapegoat coverageReport dependencyUpdatesReport copyCoverage
- sbt dependencyCheckAggregate dependencyList dependencyLicenseInfo dependencyStats makeSite
# - sbt ghpagesPushSite

notifications:
  email:
  - allixender@gmail.com
  - grmpfhmbl@gmail.com
