language: scala
sudo: required
jdk:
- oraclejdk8
scala:
- 2.11.8

before_script:
- sudo chmod +x /usr/local/bin/sbt

script:
- sbt compile coverage test scapegoat dependencyCheckAggregate coverageReport dependencyUpdatesReport copyCoverage
- sbt dependencyList dependencyLicenseInfo dependencyStats makeSite
# - sbt ghpagesPushSite

notifications:
  email:
  - allixender@gmail.com
  - grmpfhmbl@gmail.com