/**
  * Copyright (C) 2009-2016 Lightbend Inc. <https://www.lightbend.com>
  *
  * https://raw.githubusercontent.com/playframework/playframework/2.5.12/framework/src/play/src/main/scala/play/api/libs/MimeTypes.scala
  *
  * MIME type utilities.
  */

package info.smart.models.owc100

import java.util.Locale

object MimeTypes {

  /**
    * tests the MIME type for a given String.
    */
  def isKnown(mimeType: String): Option[String] = types.find(_.equals(mimeType.toLowerCase(Locale.ENGLISH)))

  def types: Array[String] = defaultTypes ++ customTypes ++ additionalText

  /**
    * tells you if mimeType is text or not.
    * Useful to determine whether the charset suffix should be attached to Content-Type or not
    * @param mimeType mimeType to check
    * @return true if mimeType is text
    */
  def isText(mimeType: String): Boolean = {
    mimeType.trim match {
      case text if text.startsWith("text/") => true
      case text if additionalText.contains(text) => true
      case _ => false
    }
  }
  
  lazy val customTypes: Array[String]  =
    """
        # GeoJson
        application/geojson
        # Atom RSS Feed is 
        application/rss+xml
        application/atom+xml
        # OGC stuffs
        application/gml+xml
        application/vnd.ogc.sld+xml
        # more science stuffs
        application/x-hdf5
    """.split('\n').map(_.trim).filter(_.size > 0).filter(_ (0) != '#')

  lazy val additionalText: Array[String] =
    """
        application/json
        application/geojson
        application/javascript
    """.split('\n').map(_.trim).filter(_.size > 0).filter(_(0) != '#')

  lazy val defaultTypes: Array[String]  =
    """
        x-world/x-3dmf
        x-world/x-3dmf
        application/x-7z-compressed
        application/octet-stream
        application/x-authorware-bin
        application/x-authorware-map
        application/x-authorware-seg
        text/vndabc
        application/x-ace-compressed
        text/html
        video/animaflex
        application/postscript
        audio/aiff
        audio/aiff
        audio/aiff
        application/x-aim
        text/x-audiosoft-intra
        application/x-alz-compressed
        application/x-navi-animation
        application/x-nokia-9000-communicator-add-on-software
        application/mime
        application/x-arc-compressed
        application/arj
        image/x-jg
        video/x-ms-asf
        text/x-asm
        text/asp
        application/x-mplayer2
        audio/basic
        video/x-msvideo
        video/avs-video
        application/x-bcpio
        application/mac-binary
        image/bmp
        application/book
        application/book
        application/x-bzip2
        application/x-bsh
        application/x-bzip2
        application/x-bzip
        text/plain
        text/x-c
        application/vnd.ms-cab-compressed
        application/vndms-pkiseccat
        text/x-c
        application/clariscad
        application/x-cocoa
        application/cdf
        application/pkix-cert
        application/x-chat
        application/x-chat
        application/vnd.kde.kchart
        application/java
        application/java-vm
        text/plain
        text/plain
        application/x-cpio
        text/x-c
        application/mac-compactpro
        application/pkcs-crl
        application/pkix-cert
        application/x-chrome-extension
        text/x-scriptcsh
        text/css
        text/csv
        text/plain
        application/x-dar
        application/x-director
        application/x-debian-package
        application/x-deepv
        text/plain
        application/x-x509-ca-cert
        application/x-font-ttf
        video/x-dv
        application/x-director
        video/divx
        video/dl
        application/x-apple-diskimage
        application/msword
        application/msword
        application/commonground
        application/drafting
        application/octet-stream
        video/x-dv
        application/x-dvi
        drawing/x-dwf=(old)
        application/x-bytecodeelisp=(compiled=elisp)
        application/acad
        application/dxf
        application/x-director
        text/x-scriptelisp
        message/rfc822
        application/x-envoy
        application/vnd.ms-fontobject
        application/postscript
        application/x-esrehber
        text/x-setext
        application/envoy
        application/octet-stream
        text/x-fortran
        text/x-fortran
        text/x-fortran
        application/vndfdf
        application/fractals
        video/fli
        image/florian
        video/x-flv
        text/vndfmiflexstor
        video/x-atomic3d-feature
        text/x-fortran
        image/vndfpx
        application/freeloader
        audio/make
        image/g3fax
        text/plain
        image/gif
        video/gl
        audio/x-gsm
        audio/x-gsm
        application/x-gsp
        application/x-gss
        application/x-gtar
        application/x-compressed
        application/x-gzip
        text/x-h
        application/x-hdf
        application/x-helpfile
        application/vndhp-hpgl
        text/x-h
        text/x-script
        application/hlp
        application/vndhp-hpgl
        application/vndhp-hpgl
        application/binhex
        application/hta
        text/x-component
        text/html
        text/html
        text/html
        text/webviewhtml
        text/html
        x-conference/x-cooltalk
        image/x-icon
        text/calendar
        text/calendar
        text/plain
        image/ief
        image/ief
        application/iges
        application/iges
        application/x-ima
        application/x-httpd-imap
        application/inf
        application/x-internett-signup
        application/x-ip2
        video/x-isvideo
        audio/it
        application/x-inventor
        i-world/i-vrml
        application/x-livescreen
        audio/x-jam
        text/x-java-source
        text/x-java-source
        application/x-java-commerce
        image/jpeg
        image/jpeg
        application/x-java-jnlp-file
        image/jpeg
        image/jpeg
        image/jpeg
        image/x-jps
        image/jpx
        application/javascript
        application/json
        image/jutvision
        audio/midi
        application/vnd.kde.karbon
        application/vnd.kde.kformula
        application/vnd.kde.kivio
        application/vnd.google-earth.kml+xml
        application/vnd.google-earth.kmz
        application/vnd.kde.kontour
        application/vnd.kde.kpresenter
        application/vnd.kde.kpresenter
        application/vnd.kde.kspread
        application/vnd.kde.kword
        application/vnd.kde.kword
        text/x-scriptksh
        audio/nspaudio
        audio/x-liveaudio
        application/x-latex
        application/lha
        application/octet-stream
        text/plain
        audio/nspaudio
        text/plain
        text/x-scriptlisp
        text/plain
        text/x-la-asf
        application/x-latex
        application/octet-stream
        application/lzx
        video/mpeg
        audio/mpeg
        video/mpeg
        audio/x-mpegurl
        text/x-m
        application/x-troff-man
        text/cache-manifest
        application/x-navimap
        text/plain
        application/mbedlet
        application/x-magic-cap-package-10
        application/mcad
        text/mcf
        application/netmc
        application/x-troff-me
        message/rfc822
        message/rfc822
        application/x-midi
        application/x-midi
        application/x-frame
        message/rfc822
        audio/x-vndaudioexplosionmjuicemediafile
        video/x-motion-jpeg
        application/base64
        application/base64
        audio/mod
        video/quicktime
        video/quicktime
        video/x-sgi-movie
        audio/mpeg
        audio/mpeg
        video/mp4
        audio/mpeg
        application/x-project
        video/mpeg
        video/mpeg
        video/mpeg
        audio/mpeg
        application/vndms-project
        application/x-project
        application/x-project
        application/x-project
        application/marc
        application/x-troff-ms
        video/x-sgi-movie
        audio/make
        application/x-vndaudioexplosionmzz
        image/naplps
        image/naplps
        application/x-netcdf
        application/vndnokiaconfiguration-message
        image/x-niff
        image/x-niff
        application/x-mix-transfer
        application/x-conference
        application/x-navidoc
        application/octet-stream
        application/oda
        application/vnd.oasis.opendocument.database
        application/vnd.oasis.opendocument.chart
        application/vnd.oasis.opendocument.formula
        application/vnd.oasis.opendocument.graphics
        application/vnd.oasis.opendocument.image
        application/vnd.oasis.opendocument.text-master
        application/vnd.oasis.opendocument.presentation
        application/vnd.oasis.opendocument.spreadsheet
        application/vnd.oasis.opendocument.text
        audio/ogg
        audio/ogg
        video/ogg
        application/x-omc
        application/x-omcdatamaker
        application/x-omcregerator
        application/vnd.oasis.opendocument.chart-template
        application/vnd.oasis.opendocument.formula-template
        application/vnd.oasis.opendocument.graphics-template
        application/vnd.oasis.opendocument.text-web
        application/vnd.oasis.opendocument.image-template
        application/vnd.oasis.opendocument.text-master
        application/vnd.oasis.opendocument.presentation-template
        application/vnd.oasis.opendocument.spreadsheet-template
        application/vnd.oasis.opendocument.text-template
        application/pkcs10
        application/pkcs-12
        application/x-pkcs7-signature
        application/pkcs7-mime
        application/pkcs7-mime
        application/x-pkcs7-certreqresp
        application/pkcs7-signature
        text/x-pascal
        application/pro_eng
        text/pascal
        image/x-portable-bitmap
        application/vndhp-pcl
        image/x-pict
        image/x-pcx
        chemical/x-pdb
        application/pdf
        audio/make
        image/x-portable-graymap
        image/pict
        image/pict
        application/x-newton-compatible-pkg
        application/vndms-pkipko
        text/x-scriptperl
        application/x-pixclscript
        application/x-pagemaker
        application/x-pagemaker
        text/x-scriptperl-module
        image/png
        application/x-portable-anymap
        application/mspowerpoint
        model/x-pov
        application/vndms-powerpoint
        image/x-portable-pixmap
        application/mspowerpoint
        application/mspowerpoint
        application/mspowerpoint
        application/x-freelance
        application/pro_eng
        application/postscript
        application/octet-stream
        paleovu/x-pv
        application/vndms-powerpoint
        text/x-scriptphyton
        application/x-bytecodepython
        audio/vndqcelp
        x-world/x-3dmf
        x-world/x-3dmf
        image/x-quicktime
        video/quicktime
        video/x-qtc
        image/x-quicktime
        image/x-quicktime
        audio/x-pn-realaudio
        audio/x-pn-realaudio
        application/x-rar-compressed
        application/x-cmu-raster
        image/cmu-raster
        application/rdf+xml
        text/x-scriptrexx
        image/vndrn-realflash
        image/x-rgb
        application/vndrn-realmedia
        audio/mid
        audio/x-pn-realaudio
        audio/x-pn-realaudio
        application/ringing-tones
        application/vndrn-realplayer
        application/x-troff
        image/vndrn-realpix
        audio/x-pn-realaudio-plugin
        text/vndrn-realtext
        application/rtf
        application/rtx
        video/vndrn-realvideo
        text/x-asm
        audio/s3m
        application/x-7z-compressed
        application/octet-stream
        application/x-tbook
        text/x-scriptscheme
        text/plain
        application/sdp
        application/sounder
        application/sea
        application/set
        text/x-sgml
        text/x-sgml
        text/x-scriptsh
        application/x-bsh
        text/x-server-parsed-html
        audio/x-psid
        application/x-koan
        application/x-koan
        application/x-koan
        application/x-koan
        application/x-stuffit
        application/x-stuffitx
        application/x-seelogo
        application/smil
        application/smil
        audio/basic
        application/solids
        text/x-speech
        application/futuresplash
        application/x-sprite
        application/x-sprite
        audio/ogg
        application/x-wais-source
        text/x-server-parsed-html
        application/streamingmedia
        application/vndms-pkicertstore
        application/step
        application/sla
        application/step
        application/x-sv4cpio
        application/x-sv4crc
        image/vnddwg
        image/svg+xml
        application/x-world
        application/x-shockwave-flash
        application/x-troff
        text/x-speech
        application/x-tar
        application/toolbook
        text/x-scripttcl
        text/x-scripttcsh
        application/x-tex
        application/x-texinfo
        application/x-texinfo
        text/plain
        application/gnutar
        image/tiff
        image/tiff
        image/x-tiff
        application/x-troff
        audio/tsp-audio
        application/dsptype
        text/tab-separated-values
        image/florian
        application/x-font-ttf
        application/x-font-ttf
        text/turtle
        text/plain
        text/x-uil
        text/uri-list
        text/uri-list
        application/i-deas
        text/uri-list
        text/uri-list
        application/x-ustar
        text/x-uuencode
        text/x-uuencode
        application/x-cdlink
        text/x-vcard
        text/x-vcard
        text/x-vcalendar
        application/vda
        video/vdo
        application/groupwise
        video/vivo
        video/vivo
        application/vocaltec-media-desc
        application/vocaltec-media-file
        audio/voc
        video/vosaic
        audio/voxware
        audio/x-twinvq-plugin
        audio/x-twinvq
        audio/x-twinvq-plugin
        application/x-vrml
        x-world/x-vrt
        application/x-visio
        application/x-visio
        application/x-visio
        application/wordperfect60
        application/wordperfect61
        application/msword
        audio/wav
        application/x-qpro
        image/vnd.wap.wbmp
        application/vndxara
        video/webm
        application/msword
        application/x-123
        windows/metafile
        text/vnd.wap.wml
        application/vnd.wap.wmlc
        text/vnd.wap.wmlscript
        application/vnd.wap.wmlscriptc
        application/font-woff
        application/font-woff2
        application/msword
        application/wordperfect
        application/wordperfect
        application/wordperfect
        application/wordperfect
        application/x-lotus
        application/mswrite
        application/x-world
        model/vrml
        text/scriplet
        application/x-wais-source
        application/x-wintalk
        image/png
        image/x-xbitmap
        video/x-amt-demorun
        xgl/drawing
        image/vndxiff
        application/excel
        application/excel
        application/excel
        application/excel
        application/excel
        application/excel
        application/excel
        application/excel
        application/excel
        application/excel
        application/excel
        application/excel
        audio/xm
        application/xml
        xgl/movie
        application/x-xpinstall
        application/x-vndls-xpix
        image/x-xpixmap
        video/x-amt-showrun
        image/x-xwd
        chemical/x-pdb
        application/x-compress
        application/zip
        application/octet-stream
        text/x-scriptzsh

        # Office 2007 mess - http://wdg.uncc.edu/Microsoft_Office_2007_MIME_Types_for_Apache_and_IIS
        application/vnd.openxmlformats-officedocument.wordprocessingml.document
        application/vnd.ms-word.document.macroEnabled.12
        application/vnd.openxmlformats-officedocument.wordprocessingml.template
        application/vnd.ms-word.template.macroEnabled.12
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        application/vnd.ms-excel.sheet.macroEnabled.12
        application/vnd.openxmlformats-officedocument.spreadsheetml.template
        application/vnd.ms-excel.template.macroEnabled.12
        application/vnd.ms-excel.sheet.binary.macroEnabled.12
        application/vnd.ms-excel.addin.macroEnabled.12
        application/vnd.openxmlformats-officedocument.presentationml.presentation
        application/vnd.ms-powerpoint.presentation.macroEnabled.12
        application/vnd.openxmlformats-officedocument.presentationml.slideshow
        application/vnd.ms-powerpoint.slideshow.macroEnabled.12
        application/vnd.openxmlformats-officedocument.presentationml.template
        application/vnd.ms-powerpoint.template.macroEnabled.12
        application/vnd.ms-powerpoint.addin.macroEnabled.12
        application/vnd.openxmlformats-officedocument.presentationml.slide
        application/vnd.ms-powerpoint.slide.macroEnabled.12
        application/vnd.ms-officetheme
        application/onenote
        application/onenote
        application/onenote
        application/onenote
        # koffice

        # iWork
        application/x-iwork-keynote-sffkey
        application/x-iwork-keynote-sffkth
        application/x-iwork-numbers-sfftemplate
        application/x-iwork-numbers-sffnumbers
        application/x-iwork-pages-sffpages
        application/x-iwork-pages-sfftemplate

        # Extensions for Mozilla apps (Firefox and friends)
        application/x-xpinstall

    """.split('\n').map(_.trim).filter(_.size > 0).filter(_ (0) != '#')



}
